version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependency-updates"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependency-updates"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependency-updates"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
