version: 2
updates:
  # npm Updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependency-updates"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "some-ignored-package"
        versions: ["<2.0.0"]

  # Composer Updates
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependency-updates"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  # GitHub Actions Updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependency-updates"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

  # Sicherheitsupdates priorisieren
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "security"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "security"
    allow:
      - dependency-type: "direct"
