version: '3.1'

services:
    db:
        image: mariadb:latest
        container_name: database
        ports:
           - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: password
        volumes:
            - ./database/init:/docker-entrypoint-initdb.d


    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATA_FILE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
