services:
    mailpit:
        image: axllent/mailpit
        container_name: bbbb-mailpit
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATA_FILE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

    database:
        image: mariadb:10.11.8
        container_name: bbbb-db
        environment:
            MARIADB_ROOT_PASSWORD: example
            MARIADB_USER: user
            MARIADB_PASSWORD: secret
            MARIADB_DATABASE: bbbb
        ports:
            - 3308:3306

    database_testing:
        image: mariadb:10.11.8
        container_name: bbbb-test-db
        environment:
            MARIADB_ROOT_PASSWORD: example
            MARIADB_USER: user
            MARIADB_PASSWORD: secret
            MARIADB_DATABASE: bbbb_testing
        ports:
            - 3307:3306
