# Use root/example as user/password credentials
version: '3.1'

services:

    db:
        image: mariadb
        ports:
            - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: test_root_password
            MARIADB_USER: test_user
            MARIADB_PASSWORD: test_password
            MARIADB_DATABASE: test_database
