openapi: 3.1.0

info:
  title: Blue Bird Big Band API
  version: v0.0.1

servers:
  - url: https://{environment}.api.bluebirdbigband.de
    variables:
      environment:
        default: prod
        enum:
          - prod
          - dev
paths:
  /musicians/grouped-by-instrument:
    get:
      summary: Get active musicians grouped by their instruments
      responses:
        '200':
          description: A list of instrument groups containing musicians
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InstrumentGroup'

  /concerts/pull:
    get:
      summary: Triggers an event to fetch new concert information from Konzertmeister
      description: Triggers an event to fetch new concert information from Konzertmeister
      security:
        - ApiKeyAuth: []
      responses:
        '204':
          description: Indicating fetching was successful
        '401':
          description: "Validierungsfehler - Die übergebenen Daten sind ungültig."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '502':
          description: Fetching data from Konzertmeister unsuccessful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /concerts/upcoming:
    get:
      summary: Get the upcoming concerts
      description: Get the upcoming concerts
      responses:
        '200':
          description: Retrieve concerts sorted by date (asc)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Concert'

components:
  schemas:
    Address:
      type: object
      properties:
        street:
          type: string
          example: "Obere Langgasse"
        house_number:
          type: string
          example: "33" # String, falls mal "33a" vorkommt
        zip_code:
          type: integer
          format: int64
          description: "5-stellige Zahl"
          example: "67346"
        city:
          type: string
          example: "Speyer"
        full_address:
          type: string
          description: "Ein vom Server vorformatierter String für die schnelle Anzeige."
          example: "Obere Langgasse 33, 67346 Speyer"

    Concert:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 101
        start_at:
          type: string
          format: date-time
          example: "2026-03-20T20:00:00Z"
        end_at:
          type: string
          format: date-time
          example: "2026-03-20T22:30:00Z"
        location_name:
          type: string
          example: "Stadthalle Speyer"
        address:
          $ref: '#/components/schemas/Address'
        description:
          type: string
          nullable: true
          example: "Swing im Dreieck"

    InstrumentGroup:
      type: object
      properties:
        name:
          type: string
          example: "Alt-Saxophon"
        image_path:
          type: string
          example: "images/instruments/alto-sax.png"
        musicians:
          type: array
          items:
            $ref: '#/components/schemas/Musician'

    Musician:
      type: object
      properties:
        name:
          type: string
          example: "Max Mustermann"

    Error:
      type: object
      properties:
        message:
          type: string
          example: "The given data was invalid."
        errors:
          type: object
          description: "Ein Objekt, bei dem die Keys die Feldnamen und die Werte Arrays von Fehlermeldungen sind."
          additionalProperties:
            type: array
            items:
              type: string

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key # Oder Authorization: Bearer
