<?php

namespace Tests\Feature\Http\Controllers\Api;

use App\Models\Instrument;
use App\Models\Musician;
use Illuminate\Testing\Fluent\AssertableJson;
use Tests\TestCase;

class MusiciansGroupedByInstrumentControllerTest extends TestCase
{
    /* Zu testen:
     * Erfolgsfall (200 OK)
     * - JSON Struktur muss passen
     * - Nur aktive Musiker sollten in Liste sein
     * - Wenn keine Musiker für ein Instrument existieren, soll liste leer sein
     * Edge-Cases:
     * - keine Musiker in DB -> leere Liste
     * */

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_single_instrument_single_musician()
    {
        $this->withoutExceptionHandling();
        $instrument = Instrument::factory()->create(['name' => 'test']);
        $musician = Musician::factory()->for($instrument)->create();
        $this->assertDatabaseCount(Musician::class, 1);
        $this->assertDatabaseCount(Instrument::class, 1);

        $response = $this->get(route('api.musicians.grouped-by-instrument'));

        var_dump($response->baseResponse->getbo);

        $response->assertOk();
        $response->assertJson(fn (AssertableJson $json) => $json->has(1)
            ->first(fn (AssertableJson $json) => $json->has('name')
                ->has('image_path')
                ->has('musicians', 1)
                ->has('musicians.0', fn (AssertableJson $json) => $json->has('name')
                )
            )
        );
    }
}
