name: Auto-Assign Reviewers

on:
  pull_request:
    types: [opened]
    branches:
      - main
      - dependency-updates

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewer
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          reviewers: |
            Mavv3006
