name: Deployment Development 3

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Laravel App to FTP Server Action
        uses: MadalitsoNyemba/laravel-deploy-to-ftp-action@release
        with:
          branch: ${{ github.ref_name }}
          php-version: '8.1'
          ftp-username-dev: ${{ secrets.ftp_username }}
          ftp-username-main: ${{ secrets.ftp_username }}
          ftp-server: ${{ secrets.ftp_server }}
          ftp-password: ${{ secrets.ftp_password }}
          use-env-files: 'true'
