name: Deployment Development

on:
  push:
    branches: [ dev ]

jobs:
  web-deploy:
    name: Deploy Fullstack Application
    runs-on: ubuntu-latest
    steps:
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: get code
        uses: actions/checkout@v3

      - name: install backend dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: install frontend dependencies
        run: |
          npm ci

      - name: setup frontend
        run: |
          npm run build

      - name: push files to server
        uses: modern-dev/ftp-mirror@v2
        with:
          server: ${{ secrets.ftp_server }}
          user: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          remote_dir: ${{ secrets.dev_dir }}
          local_dir: './'
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            .idea/**
            database/**
            **/node_modules/**
            tests/**
            .env**
            phpunit*
            docker-compose.yml
