name: Build Vue Frontend

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    name: Build Vue3 Frontend
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: get php dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: build project
        run: |
          npm ci
          npm run build
